### ISSUE TITLE
ResoureWarnings in style.py

### ISSUE THREAD

**Issue by fenchu** [pycontribs/ansi2html#174]
Hi
ansi2html is used in pytest-html to produce colorful output, but it floods the console with the following resource warnings because sockets are closed before writing the last lines, I've tracked it down to style.py, where my workaround is to just ignore the warnings. it is an harmless message.

ansi2html==1.7.0

```
(5 durations < 0.005s hidden.  Use -vv to show these durations.)
==================================================================================================================================================== 6 passed in 54.58s ==================================================================================================================================================== 
xception ignored in: <ssl.SSLSocket fd=984, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63509), raddr=('10.200.251.1', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=984, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63509), raddr=('10.200.251.1', 443)>
Exception ignored in: <ssl.SSLSocket fd=1004, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63510), raddr=('185.62.163.185', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=1004, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63510), raddr=('185.62.163.185', 443)>
Exception ignored in: <ssl.SSLSocket fd=1012, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63511), raddr=('185.62.163.183', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=1012, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63511), raddr=('185.62.163.183', 443)>
Exception ignored in: <ssl.SSLSocket fd=660, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63512), raddr=('10.200.251.1', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=660, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63512), raddr=('10.200.251.1', 443)>
Exception ignored in: <ssl.SSLSocket fd=1044, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63513), raddr=('10.200.251.1', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=1044, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63513), raddr=('10.200.251.1', 443)>
Exception ignored in: <ssl.SSLSocket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63514), raddr=('10.200.251.1', 443)>
Traceback (most recent call last):
  File "C:\dist\venvs\trk-fullstack-test\lib\site-packages\ansi2html\style.py", line 33, in __init__
    self.kwl = [(k.replace("_", "-"), kw[k][1:]) for k in sorted(kw.keys())]
ResourceWarning: unclosed <ssl.SSLSocket fd=1064, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.12.200.140', 63514), raddr=('10.200.251.1', 443)>


```

so if you add the following to the top in ansi2html/style.py you do not see them:

```
import warnings
warnings.filterwarnings("ignore", category=ResourceWarning) 
```

**Comment by hartwork** [comment]
Hi @fenchu , ansi2html doesn't do any socket handling on its own that's I'd be aware of. Could you elaborate why this issue could need addressing inside ansi2html rather than outside? Thanks!
